### ISSUE TITLE
Server sends an incorrect environment to 1.20.6 clients

### ISSUE THREAD

**Issue by AzureAaron** [HypixelDev/ModAPI#27]
On Fabric 1.20.6 the Hello S2C packet that Hypixel sends my client contains an incorrect var int index for the `PRODUCTION` enum, instead of getting a var int of 0 I get a var int of 1 which falsely indicates that my client has connected to the alpha network. The old non-event-based location packet was parsed the same way (with the PacketCodecs#indexed which uses var ints) and didn't have this issue.

The custom payload sends the following bytes to my client: `[1, 0]`
I assume the zero is to enforce implementations of the packet reading all unused bytes, unless the 1 is sent by mistake.

**Comment by ConnorLinfoot** [comment]
The first byte is the success byte, as it's still part of the standard framework the Mod API uses, it still needs to include this for the client to know how to handle following bytes.
