### ISSUE TITLE
Packet Response Identifier

### ISSUE THREAD

**Issue by My-Name-Is-Jeff** [HypixelDev/ModAPI#8]
Can the packets have an identifier (like the key field in the Minecraft ping packet) so that we know which response corresponds to which request?

**Comment by ConnorLinfoot** [comment]
With the current packets, this isn't needed, as regardless of who sends the request, all mods can listen and use the response. With the current implementation, some packets also have rate limits to reduce spam requests, so this is even more important that all mods can accept the response.

If we ever have packets based on specific information requested, then we may use identifiers for those. But right now it's not needed.
